name: Test
on: push
jobs:
  examples:
    runs-on: ubuntu-18.04
    container: clojure:openjdk-11-tools-deps-1.10.1.502-slim-buster
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@bac1a40c # We need a not-yet-released feature: https://git.io/JfBDh
        env: { cache-version: v3 }
        with:
          path: |
            .cpcache
            /root/.m2
            /root/.gitlibs
          key: ${{ runner.os }}-${{ github.workflow }}-${{ env.cache-version }}-${{ hashFiles('deps.edn') }}
      - run: bin/kaocha examples
